# Lesson 9 Complete Solution: Advanced CRUD Operations & Transactions Configuration

spring:
  profiles:
    active: dev
    
  # H2 Database Configuration for Development
  datasource:
    url: jdbc:h2:mem:lesson9db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    
  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true
        
  # H2 Console Configuration
  h2:
    console:
      enabled: true
      path: /h2-console
      
  # Transaction Configuration
  transaction:
    default-timeout: 300  # 5 minutes default timeout
    rollback-on-commit-failure: true
      
# Logging Configuration
logging:
  level:
    com.learning.crud: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.orm.jpa: DEBUG

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,beans,auditevents
  endpoint:
    health:
      show-details: always

---
# Production Profile Configuration
spring:
  config:
    activate:
      on-profile: prod
      
  # PostgreSQL Configuration for Production
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:lesson9_prod}
    username: ${DB_USER:lesson9}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
  # Production Transaction Settings
  transaction:
    default-timeout: 60  # 1 minute for production

---
# Test Profile Configuration
spring:
  config:
    activate:
      on-profile: test
      
  # Test Database Configuration
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false