spring:
  application:
    name: async-workshop
  
  datasource:
    url: jdbc:h2:mem:async_db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console

# TODO: Add async configuration
# async:
#   thread-pools:
#     general:
#       core-size: 5
#       max-size: 20
#       queue-capacity: 100
#     fast:
#       core-size: 10
#       max-size: 50
#       queue-capacity: 25
#     heavy:
#       core-size: 2
#       max-size: 8
#       queue-capacity: 500
  
# TODO: Add scheduling configuration  
# scheduling:
#   pool-size: 5
  
logging:
  level:
    com.learning.async: DEBUG
    org.springframework.scheduling: DEBUG