# Lesson 9 Workshop: Advanced CRUD Operations & Transactions Configuration

spring:
  profiles:
    active: dev
    
  # TODO: Configure H2 database for development
  datasource:
    # TODO: Add H2 database URL (jdbc:h2:mem:lesson9db)
    # TODO: Add username and password
    # TODO: Add H2 driver class name
    
  # TODO: Configure JPA/Hibernate settings
  jpa:
    # TODO: Set hibernate.ddl-auto to create-drop for development
    # TODO: Enable show-sql for development
    # TODO: Configure hibernate properties
    hibernate:
      # TODO: Add ddl-auto setting
    # TODO: Add show-sql setting
    properties:
      hibernate:
        # TODO: Add H2 dialect
        # TODO: Enable SQL formatting
        # TODO: Configure batch settings for bulk operations
        
  # TODO: Configure H2 console for development
  h2:
    console:
      # TODO: Enable H2 console
      
  # TODO: Configure transaction management
  transaction:
    # TODO: Set default timeout
    # TODO: Configure rollback behavior
      
# TODO: Configure logging levels
logging:
  level:
    # TODO: Set com.learning.crud to DEBUG
    # TODO: Set org.springframework.transaction to DEBUG
    # TODO: Set org.hibernate.SQL to DEBUG (for SQL logging)
    # TODO: Set org.hibernate.type.descriptor.sql.BasicBinder to TRACE (for parameter logging)

# TODO: Configure management endpoints
management:
  endpoints:
    web:
      exposure:
        # TODO: Include health, info, metrics endpoints

---
# TODO: Production profile configuration
spring:
  config:
    activate:
      on-profile: prod
      
  # TODO: Configure PostgreSQL for production
  datasource:
    # TODO: Add PostgreSQL URL with environment variables
    # TODO: Add username and password from environment
    # TODO: Add PostgreSQL driver
    
  jpa:
    hibernate:
      # TODO: Change ddl-auto to validate for production
    # TODO: Disable show-sql in production
    properties:
      hibernate:
        # TODO: Add PostgreSQL dialect
        
---
# TODO: Test profile configuration
spring:
  config:
    activate:
      on-profile: test
      
  # TODO: Configure test database settings
  datasource:
    # TODO: Configure test database (H2 in-memory)
    
  jpa:
    hibernate:
      # TODO: Use create-drop for tests