# Lesson 12 Complete Solution: Authentication & JWT Security Configuration

spring:
  profiles:
    active: dev
    
  # H2 Database Configuration for Development
  datasource:
    url: jdbc:h2:mem:securitydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    
  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true
        
  # H2 Console Configuration
  h2:
    console:
      enabled: true
      path: /h2-console
      
  # Jackson Configuration
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL

# JWT Configuration
jwt:
  secret: mySecretKeyThatIsLongEnoughForHMACSignatureAlgorithmAndMustBeAtLeast256BitsForHS256
  expiration: 86400000 # 24 hours in milliseconds
  refresh:
    expiration: 604800000 # 7 days in milliseconds

# Security Configuration
security:
  cors:
    allowed-origins: "http://localhost:3000,http://localhost:8080"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"
    allow-credentials: true
  rate-limit:
    requests-per-minute: 100

# Logging Configuration
logging:
  level:
    com.learning.security: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

---
# Test Profile Configuration
spring:
  config:
    activate:
      on-profile: test
      
  # Test Database Configuration
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

# Test JWT Configuration (shorter expiration for testing)
jwt:
  secret: testSecretKeyThatIsLongEnoughForHMACSignatureAlgorithmForTestingPurposes
  expiration: 60000 # 1 minute for testing
  refresh:
    expiration: 300000 # 5 minutes for testing