# Lesson 8 Complete Solution: Dual Database Configuration

spring:
  profiles:
    active: dev
    
  # H2 Database Configuration for Development
  datasource:
    url: jdbc:h2:mem:lesson8db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    
  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        
  # H2 Console Configuration
  h2:
    console:
      enabled: true
      path: /h2-console
      
  # MongoDB Configuration
  data:
    mongodb:
      database: lesson8_mongo
      auto-index-creation: true
      
# Logging Configuration
logging:
  level:
    com.learning.persistence: DEBUG
    org.springframework.data: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,beans
  endpoint:
    health:
      show-details: always

---
# Production Profile Configuration
spring:
  config:
    activate:
      on-profile: prod
      
  # PostgreSQL Configuration for Production
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:lesson8_prod}
    username: ${DB_USER:lesson8}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
  # MongoDB Production Configuration
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DB:lesson8_prod}

---
# Test Profile Configuration
spring:
  config:
    activate:
      on-profile: test
      
  # Embedded MongoDB for Testing
  mongodb:
    embedded:
      version: 4.4.18
      
  # Test Database Configuration
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false